version: '3'

services:
  webapp:
    image: railway-routing-service:1.0.0
    container_name: railway-routing-service
    environment:
      RAILWAY_CSVPATH: /var/lib/railway-routing-service/StationMap.csv
    ports:
      - 80:8080
    volumes:
      - /var/lib/railway-routing-service:/var/lib/railway-routing-service