- hosts: os
  gather_facts: no
  pre_tasks:
    - name: 'apt-get update'
      raw: sudo apt-get update
    - name: 'install python3'
      raw: sudo apt-get -y install python3 python3-pip
    - name: 'upgrade pip3'
      raw: pip3 install --upgrade pip
    - name: 'pip3 install docker'
      raw: pip3 install docker
    - name: 'Gathering Facts'
      setup:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: os